repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
        additional_dependencies: [
            pydantic==2.3.0,
        ]
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        args: [src, tests]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [src, tests]
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.0
    hooks:
    -   id: autoflake
        args: ["--in-place", "--remove-all-unused-imports"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
