"""init

Revision ID: 0341fcd398cf
Revises:
Create Date: 2023-08-31 21:46:38.194803

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0341fcd398cf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transaction",
        sa.Column("tx_id", sa.String(), nullable=False),
        sa.Column("tx_result", sa.String(), nullable=True),
        sa.Column("payload", sa.String(), nullable=False),
        sa.Column("signer", sa.String(), nullable=False),
        sa.Column("nonce", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("tx_id"),
        sa.UniqueConstraint("signer", "nonce"),
    )
    op.create_index(
        op.f("ix_transaction_signer"), "transaction", ["signer"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transaction_signer"), table_name="transaction")
    op.drop_table("transaction")
    # ### end Alembic commands ###
