name: run test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'poetry'
      - run: poetry install
      - name: pre-commit
        uses: pre-commit/action@v3.0.0
      - name: Setup Postgres database
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          postgres_image_tag: 12-alpine
          postgres_password: ${{ secrets.DB_PASS }}
      - name: actions-setup-redis
        uses: shogo82148/actions-setup-redis@v1.19.0
        with:
          redis-version: 7
          auto-start: false
      - name: Test with pytest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          KMS_KEY_ID: ${{ secrets.KMS_KEY_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          CELERY_BROKER_URL: ${{ secrets.CELERY_BROKER_URL }}
          CELERY_RESULT_BACKEND: ${{ secrets.CELERY_RESULT_BACKEND }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          HEADLESS_URL: ${{ secrets.HEADLESS_URL }}
        run: |
          poetry run pytest --redis-exec=$(which redis-server) --ignore tests/tasks_test.py --cov src --cov-report=xml
          poetry run pytest --redis-exec=$(which redis-server) tests/tasks_test.py
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
